- name: Ansible no Azure
  href: ./index.yml
- name: Visão geral
  items:
    - name: Sobre o Ansible no Azure
      href: ./ansible-overview.md
- name: Guia de início rápido
  expanded: true
  items:
    - name: Instalar e configurar Ansible
      href: /azure/virtual-machines/linux/ansible-install-configure
      maintainContext: true
    - name: Criar uma VM do Linux
      href: /azure/virtual-machines/linux/ansible-create-vm
      maintainContext: true
- name: Tutoriais
  items:
    - name: Criar uma VM completa do Linux
      href: /azure/virtual-machines/linux/ansible-create-complete-vm
      maintainContext: true
    - name: Executar um manual no Cloud Shell
      href: ./ansible-run-playbook-in-cloudshell.md
      maintainContext: true
    - name: Gerenciar inventários dinâmicos
      href: ./ansible-manage-azure-dynamic-inventories.md
      maintainContext: true
- name: Referência
  items:
    - name: Funções do manual
      items:
        - name: azure_module
          href: 'https://galaxy.ansible.com/Azure/azure_modules/'
        - name: azure_preview_module
          href: 'https://galaxy.ansible.com/Azure/azure_preview_modules'
    - name: Versões e recursos
      href: ./ansible-matrix.md
    - name: Instâncias de Contêiner do Azure
      href: 'http://docs.ansible.com/ansible/latest/azure_rm_acs_module.html'
    - name: Funções do Azure
      href: 'http://docs.ansible.com/ansible/latest/azure_rm_functionapp_module.html'
    - name: Balanceadores de carga
      href: 'http://docs.ansible.com/ansible/latest/azure_rm_loadbalancer_module.html'
    - name: Máquinas virtuais
      href: 'http://docs.ansible.com/ansible/latest/azure_rm_virtualmachine_module.html'
    - name: Todos os módulos do Azure
      href: 'http://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#azure'